name = "telegram-monitor"
compatibility_date = "2025-09-12"
main = "index.js"  # Если index.js в корне, укажите "index.js"; если в src/, укажите "src/index.js"

# Настройка KV Namespace
[[kv_namespaces]]
binding = "STATUS_KV"
id = "<ваш_KV_namespace_id>"

# Переменные окружения
[vars]
MATTERMOST_WEBHOOK = "<https://mm.mvpproject.io/hooks/1q715bsjzina5enz98x43bj7gc>"
BOT_TOKEN = "<7564679631:AAFW9v0LAO_6jFJVbIcOhIB-5g7mj6Oc8XA>"
TEST_CHAT_ID = "<ваш_чат_id>"  # Замените на реальный chat_id
MIN_CONSECUTIVE_FAILURES = 2
CHECK_HOST_MAX_NODES = 5
CHECK_HOST_FAIL_NODES = 2
MAX_RESPONSE_TIME_MS = 2000
